server:
   servlet:
      context-path: /ratings-data-service-0.0.1-SNAPSHOT
spring:
  application:
    jmx:
      default-domain: ratings-data-service
  cloud:
    config:
      override-system-properties: false
